### ISSUE TITLE
Safe area padding effect

### ISSUE THREAD

**Issue by stackunderflows** [OSTUSA/PhantomLib#4]
Keep content out of the safe area on iOS. Maybe this is needed with Android Q also?

**Comment by tbrushwyler** [comment]
Xamarin.Forms has a [default implementation of this](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/ios/page-safe-area-layout). Not sure if that captures this issue or if there are other enhancements.

**Comment by tbrushwyler** [comment]
This was merged in #29
